"""Update timetable

Revision ID: 039c114bdb53
Revises: 7b2511cf8da6
Create Date: 2022-04-07 02:23:53.874177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '039c114bdb53'
down_revision = '7b2511cf8da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('meeting_link', sa.String(length=300), nullable=True))
    op.drop_constraint('timetable_ibfk_1', 'timetable', type_='foreignkey')
    op.drop_column('timetable', 'class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('timetable_ibfk_1', 'timetable', 'classes', ['class_id'], ['id'])
    op.drop_column('timetable', 'meeting_link')
    # ### end Alembic commands ###
