"""Update calendar

Revision ID: 0fdc5ee5f004
Revises: 039c114bdb53
Create Date: 2022-04-07 02:46:25.326324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fdc5ee5f004'
down_revision = '039c114bdb53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calendar_ibfk_2', 'calendar', type_='foreignkey')
    op.drop_column('calendar', 'class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('calendar_ibfk_2', 'calendar', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###
