"""Update class foriegn key

Revision ID: 39176b01f004
Revises: 4ff8d7e74afa
Create Date: 2022-03-25 02:34:42.697981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39176b01f004'
down_revision = '4ff8d7e74afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'calendar', 'classes', ['class_id'], ['name'])
    op.create_foreign_key(None, 'students', 'classes', ['class_id'], ['name'])
    op.create_foreign_key(None, 'subject_class_map', 'classes', ['class_id'], ['name'])
    op.create_foreign_key(None, 'teacher_class_map', 'classes', ['class_id'], ['name'])
    op.create_foreign_key(None, 'timetable', 'classes', ['class_id'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'teacher_class_map', type_='foreignkey')
    op.drop_constraint(None, 'subject_class_map', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'calendar', type_='foreignkey')
    # ### end Alembic commands ###
