"""Add classes and subjects

Revision ID: 78ffa43f1aaa
Revises: 3e168d68810d
Create Date: 2021-11-08 16:50:52.989948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ffa43f1aaa'
down_revision = '3e168d68810d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'class_id')
    op.drop_table('classes')
    # ### end Alembic commands ###
