"""Update marks to submissions

Revision ID: 7b2511cf8da6
Revises: 9d78b2b5c348
Create Date: 2022-04-07 01:54:18.328736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b2511cf8da6'
down_revision = '9d78b2b5c348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('attachement', sa.String(length=1000), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('marks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assignment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marks', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='marks_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='marks_ibfk_2'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='marks_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('submissions')
    # ### end Alembic commands ###
