"""Add max marks in assignments

Revision ID: e039e16839a0
Revises: 1af686be57f7
Create Date: 2022-04-03 16:42:23.373264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e039e16839a0'
down_revision = '1af686be57f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('max_marks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'max_marks')
    # ### end Alembic commands ###
